(define-module (canary cmd)
  #:use-module (canary engine-types)
  #:use-module (canary backend)
  #:use-module (canary backend-ansi)
  #:use-module (canary theme)
  #:use-module (canary protocol)
  #:use-module (fibers)
  #:use-module ((fibers timers) #:select ((sleep . fiber-sleep)))
  #:export (run-command))

;; Cmd interpreter. Cmds are values returned by node react procs (and
;; by init procs). The engine calls (run-command eng cmd) per cmd.
;;
;; ENG is the <engine> from (canary engine-types). The send and
;; log/stop hooks are passed in so cmd.scm doesn't need to import the
;; engine loop module (which would create a cycle).
(define (run-command eng cmd send! stop! log!)
  (cond
   ((not cmd) #f)
   ((eq? cmd 'quit) (stop!))
   ((clear-screen? cmd)
    (set! (ansi-backend-prev-term (engine-backend eng)) #f))
   ((set-title? cmd)
    (let ((out (ansi-backend-port (engine-backend eng))))
      (display (string-append "\x1b]0;" (set-title-text cmd) "\x07") out)
      (force-output out)))
   ((cursor? cmd)
    (let ((out (ansi-backend-port (engine-backend eng))))
      (case (cursor-mode cmd)
        ((hidden hide) (display "\x1b[?25l" out))
        ((visible show) (display "\x1b[?25h" out))
        ((bar)         (display "\x1b[5 q" out))
        ((underline)   (display "\x1b[3 q" out))
        ((block)       (display "\x1b[1 q" out)))
      (force-output out)))
   ((alt-screen? cmd)
    (let ((out (ansi-backend-port (engine-backend eng))))
      (display (if (alt-screen-on? cmd) "\x1b[?1049h" "\x1b[?1049l") out)
      (force-output out)))
   ((mouse-mode? cmd)
    (let ((out (ansi-backend-port (engine-backend eng))))
      (case (mouse-mode-kind cmd)
        ((off)
         (display "\x1b[?1006l\x1b[?1015l\x1b[?1002l\x1b[?1003l\x1b[?1000l" out))
        ((click)
         (display "\x1b[?1003l\x1b[?1002l\x1b[?1000h\x1b[?1006h" out))
        ((cell)
         (display "\x1b[?1003l\x1b[?1002h\x1b[?1006h" out))
        ((all)
         (display "\x1b[?1003h\x1b[?1006h" out)))
      (force-output out)))
   ((println? cmd)
    (let ((out  (ansi-backend-port (engine-backend eng)))
          (line (apply string-append
                       (map (lambda (p) (if (string? p) p (format #f "~a" p)))
                            (println-parts cmd)))))
      (display "\x1b[?1049l" out)
      (display line out)
      (newline out)
      (display "\x1b[?1049h" out)
      (set! (ansi-backend-prev-term (engine-backend eng)) #f)
      (force-output out)))
   ((set-palette? cmd)
    (when (theme-set! (engine-theme eng) (set-palette-name cmd))
      (set! (ansi-backend-prev-term (engine-backend eng)) #f)))
   ((cycle-palette? cmd)
    (theme-cycle! (engine-theme eng))
    (set! (ansi-backend-prev-term (engine-backend eng)) #f))
   ((clear-log? cmd) (set-engine-log-entries! eng '()))
   ((suspend? cmd)
    (let ((sigtstp 20))                ; Linux SIGTSTP
      (backend-shutdown (engine-backend eng))
      (kill (getpid) sigtstp)
      (backend-init (engine-backend eng))
      (send! (resumed))))
   ((exec? cmd)
    (let ((command (exec-command cmd))
          (on-done (exec-on-done cmd)))
      (backend-shutdown (engine-backend eng))
      (let ((status (system command)))
        (backend-init (engine-backend eng))
        (when on-done
          (let ((msg (on-done status)))
            (when msg (send! msg)))))))
   ((batch? cmd)
    (for-each (lambda (c) (run-command eng c send! stop! log!)) (cdr cmd)))
   ((sequence? cmd)
    (spawn-fiber
     (lambda ()
       (catch #t
         (lambda ()
           (for-each (lambda (c)
                       (when (and c (engine-running? eng))
                         (let ((msg (c)))
                           (when msg (send! msg)))))
                     (cdr cmd)))
         (lambda (key . args)
           (log! 'cmd 'error (format #f "~a ~a" key args)))))))
   ((every? cmd)
    (let ((period   (cadr cmd))
          (producer (caddr cmd)))
      (spawn-fiber
       (lambda ()
         (let loop ()
           (when (engine-running? eng)
             (fiber-sleep period)
             (catch #t
               (lambda ()
                 (let ((msg (producer)))
                   (when msg (send! msg))))
               (lambda (key . args)
                 (log! 'cmd 'error (format #f "every: ~a ~a" key args))))
             (loop)))))))
   ((after? cmd)
    (let ((delay    (cadr cmd))
          (producer (caddr cmd)))
      (spawn-fiber
       (lambda ()
         (fiber-sleep delay)
         (when (engine-running? eng)
           (catch #t
             (lambda ()
               (let ((msg (producer)))
                 (when msg (send! msg))))
             (lambda (key . args)
               (log! 'cmd 'error (format #f "after: ~a ~a" key args)))))))))
   ((procedure? cmd)
    (spawn-fiber
     (lambda ()
       (catch #t
         (lambda ()
           (let ((msg (cmd)))
             (when msg (send! msg))))
         (lambda (key . args)
           (log! 'cmd 'error (format #f "~a ~a" key args)))))))))
