(define-module (canary term ops)
  #:use-module (canary term types)
  #:export (term-cursor-up!
            term-cursor-down!
            term-cursor-left!
            term-cursor-right!
            term-cursor-horizontal-abs!
            term-cursor-vertical-abs!
            term-goto!
            term-save-cursor!
            term-restore-cursor!
            term-erase-in-line!
            term-erase-in-display!
            term-erase-char!
            term-insert-char!
            term-delete-char!
            term-insert-line!
            term-delete-line!
            term-scroll-up!
            term-scroll-down!
            term-horizontal-tab!
            term-horizontal-backtab!
            term-index!
            term-reverse-index!
            term-line-feed!
            term-carriage-return!
            term-set-scroll-region!
            term-enter-alt-screen!
            term-exit-alt-screen!
            term-current-bg-face))

(define (clamp-min v lo)
  (if (< v lo) lo v))

(define* (term-cursor-right! term #:optional (n 1))
  (let ((n (clamp-min n 1))
        (max-x (- (term-width term) 1)))
    (set-term-cursor-x! term (min (+ (term-cursor-x term) n) max-x))))

(define* (term-cursor-left! term #:optional (n 1))
  (let ((n (clamp-min n 1)))
    (set-term-cursor-x! term (max (- (term-cursor-x term) n) 0))))

(define* (term-cursor-down! term #:optional (n 1))
  (let ((n (clamp-min n 1))
        (max-y (- (term-height term) 1)))
    (set-term-cursor-y! term (min (+ (term-cursor-y term) n) max-y))))

(define* (term-cursor-up! term #:optional (n 1))
  (let ((n (clamp-min n 1)))
    (set-term-cursor-y! term (max (- (term-cursor-y term) n) 0))))

(define* (term-cursor-horizontal-abs! term #:optional (n 1))
  (set-term-cursor-x! term (min (max (- n 1) 0) (- (term-width term) 1))))

(define* (term-cursor-vertical-abs! term #:optional (n 1))
  (set-term-cursor-y! term (min (max (- n 1) 0) (- (term-height term) 1))))

(define* (term-goto! term #:optional (y 1) (x 1))
  (set-term-cursor-y! term (min (max (- (or y 1) 1) 0) (- (term-height term) 1)))
  (set-term-cursor-x! term (min (max (- (or x 1) 1) 0) (- (term-width term) 1))))

(define (term-save-cursor! term)
  (set-term-saved-cursor-x! term (term-cursor-x term))
  (set-term-saved-cursor-y! term (term-cursor-y term))
  (set-term-saved-attrs! term (copy-face-attrs (term-attrs term))))

(define (term-restore-cursor! term)
  (set-term-cursor-x! term (term-saved-cursor-x term))
  (set-term-cursor-y! term (term-saved-cursor-y term))
  (let ((saved (term-saved-attrs term)))
    (when saved
      (let ((cur (term-attrs term)))
        (set-face-fg! cur (face-fg saved))
        (set-face-bg! cur (face-bg saved))
        (set-face-bold! cur (face-bold? saved))
        (set-face-faint! cur (face-faint? saved))
        (set-face-italic! cur (face-italic? saved))
        (set-face-underline! cur (face-underline saved))
        (set-face-ul-color! cur (face-ul-color saved))
        (set-face-blink! cur (face-blink saved))
        (set-face-inverse! cur (face-inverse? saved))
        (set-face-conceal! cur (face-conceal? saved))
        (set-face-crossed! cur (face-crossed? saved))))))

(define (term-current-bg-face term)
  (and (face-bg (term-attrs term))
       (let ((cur (term-attrs term))
             (cached (term-last-write-face term)))
         (if (and cached (face-attrs-equal? cached cur))
             cached
             (let ((c (copy-face-attrs cur)))
               (set-term-last-write-face! term c)
               c)))))

(define (clear-cell! cell face)
  (set-cell-char! cell #\space)
  (set-cell-face! cell face))

(define* (term-erase-in-line! term #:optional (mode 0))
  (let* ((y (term-cursor-y term))
         (x (term-cursor-x term))
         (w (term-width term))
         (row (term-grid-row term y))
         (face (term-current-bg-face term)))
    (case mode
      ((0)
       (do ((i x (+ i 1)))
           ((= i w))
         (clear-cell! (vector-ref row i) face)))
      ((1)
       (do ((i 0 (+ i 1)))
           ((> i x))
         (clear-cell! (vector-ref row i) face)))
      ((2)
       (do ((i 0 (+ i 1)))
           ((= i w))
         (clear-cell! (vector-ref row i) face))))))

(define* (term-erase-in-display! term #:optional (mode 0))
  (let* ((y (term-cursor-y term))
         (h (term-height term))
         (face (term-current-bg-face term))
         (grid (term-grid term)))
    (case mode
      ((0)
       (term-erase-in-line! term 0)
       (do ((i (+ y 1) (+ i 1)))
           ((= i h))
         (clear-row! (vector-ref grid i) face)))
      ((1)
       (do ((i 0 (+ i 1)))
           ((= i y))
         (clear-row! (vector-ref grid i) face))
       (term-erase-in-line! term 1))
      ((2 3)
       (clear-grid! grid face)
       (when (= mode 3)
         (set-term-scrollback-size! term 0))))))

(define* (term-erase-char! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (y (term-cursor-y term))
         (x (term-cursor-x term))
         (w (term-width term))
         (row (term-grid-row term y))
         (count (min n (- w x)))
         (face (term-current-bg-face term)))
    (do ((i x (+ i 1)))
        ((= i (+ x count)))
      (clear-cell! (vector-ref row i) face))))

(define* (term-insert-char! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (y (term-cursor-y term))
         (x (term-cursor-x term))
         (w (term-width term))
         (row (term-grid-row term y))
         (count (min n (- w x)))
         (face (term-current-bg-face term)))
    (do ((i (- w 1) (- i 1)))
        ((< i (+ x count)))
      (let ((src (vector-ref row (- i count)))
            (dst (vector-ref row i)))
        (set-cell-char! dst (cell-char src))
        (set-cell-face! dst (cell-face src))))
    (do ((i x (+ i 1)))
        ((= i (+ x count)))
      (clear-cell! (vector-ref row i) face))))

(define* (term-delete-char! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (y (term-cursor-y term))
         (x (term-cursor-x term))
         (w (term-width term))
         (row (term-grid-row term y))
         (count (min n (- w x)))
         (face (term-current-bg-face term)))
    (do ((i x (+ i 1)))
        ((= i (- w count)))
      (let ((src (vector-ref row (+ i count)))
            (dst (vector-ref row i)))
        (set-cell-char! dst (cell-char src))
        (set-cell-face! dst (cell-face src))))
    (do ((i (- w count) (+ i 1)))
        ((= i w))
      (clear-cell! (vector-ref row i) face))))

(define (push-scrollback! term row)
  (let ((sb (term-scrollback term))
        (max-sb (term-max-scrollback term)))
    (when (and sb (positive? max-sb))
      (when (>= (term-scrollback-size term) (vector-length sb))
        (let* ((cap (vector-length sb))
               (new-cap (min (* 2 (max cap 64)) max-sb))
               (new (make-vector new-cap #f)))
          (do ((i 0 (+ i 1)))
              ((= i (term-scrollback-size term)))
            (vector-set! new i (vector-ref sb i)))
          (set-term-scrollback! term new)
          (set! sb new)))
      (when (< (term-scrollback-size term) max-sb)
        (vector-set! sb (term-scrollback-size term) (copy-row row))
        (set-term-scrollback-size! term (+ (term-scrollback-size term) 1))))))

(define* (term-scroll-up! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (top (term-scroll-top term))
         (bot (term-scroll-bottom term))
         (region-height (+ 1 (- bot top)))
         (count (min n region-height))
         (grid (term-grid term)))
    (when (positive? count)
      (when (and (zero? top) (not (term-in-alt? term)))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (push-scrollback! term (vector-ref grid (+ top i)))))
      (let ((saved (make-vector count #f)))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (vector-set! saved i (vector-ref grid (+ top i))))
        (do ((i top (+ i 1)))
            ((> i (- bot count)))
          (vector-set! grid i (vector-ref grid (+ i count))))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (let ((row (vector-ref saved i)))
            (clear-row! row)
            (vector-set! grid (+ bot (- count) 1 i) row)))))))

(define* (term-scroll-down! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (top (term-scroll-top term))
         (bot (term-scroll-bottom term))
         (region-height (+ 1 (- bot top)))
         (count (min n region-height))
         (grid (term-grid term)))
    (when (positive? count)
      (let ((saved (make-vector count #f)))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (vector-set! saved i (vector-ref grid (+ bot (- count) 1 i))))
        (do ((i bot (- i 1)))
            ((< i (+ top count)))
          (vector-set! grid i (vector-ref grid (- i count))))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (let ((row (vector-ref saved i)))
            (clear-row! row)
            (vector-set! grid (+ top i) row)))))))

(define* (term-insert-line! term #:optional (n 1))
  (let ((n (clamp-min n 1))
        (y (term-cursor-y term))
        (top (term-scroll-top term))
        (bot (term-scroll-bottom term)))
    (when (and (>= y top) (<= y bot))
      (let ((old-top top))
        (set-term-scroll-top! term y)
        (term-scroll-down! term (min n (+ 1 (- bot y))))
        (set-term-scroll-top! term old-top)))))

(define* (term-delete-line! term #:optional (n 1))
  (let ((n (clamp-min n 1))
        (y (term-cursor-y term))
        (top (term-scroll-top term))
        (bot (term-scroll-bottom term)))
    (when (and (>= y top) (<= y bot))
      (let ((old-top top))
        (set-term-scroll-top! term y)
        (term-scroll-up! term (min n (+ 1 (- bot y))))
        (set-term-scroll-top! term old-top)))))

(define* (term-horizontal-tab! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (x (term-cursor-x term))
         (w (term-width term))
         (next-tab (+ x (- 8 (modulo x 8)))))
    (do ((i 1 (+ i 1)))
        ((= i n))
      (set! next-tab (+ next-tab 8)))
    (set-term-cursor-x! term (min next-tab (- w 1)))))

(define* (term-horizontal-backtab! term #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (x (term-cursor-x term))
         (prev-tab (if (zero? (modulo x 8))
                       (- x 8)
                       (- x (modulo x 8)))))
    (do ((i 1 (+ i 1)))
        ((= i n))
      (set! prev-tab (- prev-tab 8)))
    (set-term-cursor-x! term (max prev-tab 0))))

(define (term-index! term)
  (let ((y (term-cursor-y term))
        (bot (term-scroll-bottom term)))
    (cond
     ((= y bot) (term-scroll-up! term 1))
     ((< y (- (term-height term) 1))
      (set-term-cursor-y! term (+ y 1))))))

(define (term-reverse-index! term)
  (let ((y (term-cursor-y term))
        (top (term-scroll-top term)))
    (cond
     ((= y top) (term-scroll-down! term 1))
     ((> y 0)
      (set-term-cursor-y! term (- y 1))))))

(define (term-line-feed! term)
  (let* ((y (term-cursor-y term))
         (bot (term-scroll-bottom term)))
    (set-term-cursor-x! term 0)
    (cond
     ((= y bot) (term-scroll-up! term 1))
     ((< y (- (term-height term) 1))
      (set-term-cursor-y! term (+ y 1))))))

(define (term-carriage-return! term)
  (set-term-cursor-x! term 0))

(define* (term-set-scroll-region! term #:optional top bottom)
  (let ((tv (or top 1))
        (bv (or bottom (term-height term))))
    (when (and (< 0 tv) (< tv bv) (<= bv (term-height term)))
      (set-term-scroll-top! term (- tv 1))
      (set-term-scroll-bottom! term (- bv 1))
      (term-goto! term 1 1))))

(define (term-enter-alt-screen! term)
  (unless (term-in-alt? term)
    (set-term-main-grid! term (term-grid term))
    (set-term-grid! term (make-grid (term-width term) (term-height term)))
    (set-term-in-alt! term #t)
    (term-goto! term 1 1)))

(define (term-exit-alt-screen! term)
  (when (term-in-alt? term)
    (set-term-grid! term (term-main-grid term))
    (set-term-main-grid! term #f)
    (set-term-in-alt! term #f)))
