(define-module (canary term write)
  #:use-module (canary term types)
  #:use-module (canary term ops)
  #:export (term-write!
            char-display-width))

(define *dec-line-drawing*
  (let ((h (make-hash-table)))
    (for-each (lambda (pair)
                (hash-set! h (car pair) (cdr pair)))
              '((#\+ . #\→) (#\, . #\←) (#\- . #\↑) (#\. . #\↓)
                (#\0 . #\█) (#\` . #\◆) (#\a . #\▒) (#\f . #\°)
                (#\g . #\±) (#\h . #\░) (#\i . #\#)
                (#\j . #\┘) (#\k . #\┐) (#\l . #\┌) (#\m . #\└)
                (#\n . #\┼) (#\o . #\⎺) (#\p . #\⎻) (#\q . #\─)
                (#\r . #\⎼) (#\s . #\⎽) (#\t . #\├) (#\u . #\┤)
                (#\v . #\┴) (#\w . #\┬) (#\x . #\│) (#\y . #\≤)
                (#\z . #\≥) (#\{ . #\π) (#\| . #\≠) (#\} . #\£)
                (#\~ . #\•)))
    h))

(define (translate-charset ch charset)
  (case charset
    ((dec-line-drawing)
     (or (hash-ref *dec-line-drawing* ch) ch))
    (else ch)))

(define (current-charset-mapping term)
  (case (term-active-charset term)
    ((g0) (term-g0 term))
    ((g1) (term-g1 term))
    ((g2) (term-g2 term))
    ((g3) (term-g3 term))
    (else 'us-ascii)))

(define (char-display-width ch)
  (let ((code (char->integer ch)))
    (cond
     ((< code 32) 0)
     ((= code #x7F) 0)
     ((or (and (<= #x0300 code) (<= code #x036F))
          (and (<= #x0483 code) (<= code #x0489))
          (and (<= #x0591 code) (<= code #x05C7))
          (and (<= #x064B code) (<= code #x065F))
          (and (<= #x200B code) (<= code #x200F))
          (and (<= #x20D0 code) (<= code #x20FF))
          (and (<= #xFE20 code) (<= code #xFE2F)))
      0)
     ((or (and (<= #x1100 code) (<= code #x115F))
          (and (<= #x2E80 code) (<= code #x2FFF))
          (and (<= #x3000 code) (<= code #x9FFF))
          (and (<= #xAC00 code) (<= code #xD7A3))
          (and (<= #xF900 code) (<= code #xFAFF))
          (and (<= #xFF01 code) (<= code #xFF60))
          (and (<= #x1F300 code) (<= code #x1F9FF)))
      2)
     (else 1))))

(define (current-write-face term)
  (let ((cur (term-attrs term))
        (cached (term-last-write-face term)))
    (if (and cached (face-attrs-equal? cached cur))
        cached
        (let ((c (copy-face-attrs cur)))
          (set-term-last-write-face! term c)
          c))))

(define* (term-write! term str #:optional (start 0) (end #f))
  (let* ((end (or end (string-length str)))
         (w (term-width term))
         (charset (current-charset-mapping term))
         (face (current-write-face term)))
    (let loop ((idx start))
      (when (< idx end)
        (let* ((raw (string-ref str idx))
               (ch (translate-charset raw charset))
               (cw (char-display-width ch)))
          (unless (zero? cw)
            (set-term-last-char! term ch)
            (when (term-insert? term)
              (term-insert-char! term cw))
            (when (>= (term-cursor-x term) w)
              (cond
               ((term-auto-margin? term)
                (set-term-cursor-x! term 0)
                (cond
                 ((= (term-cursor-y term) (term-scroll-bottom term))
                  (term-scroll-up! term 1))
                 (else
                  (set-term-cursor-y! term (+ (term-cursor-y term) 1)))))
               (else
                (set-term-cursor-x! term (- w 1)))))
            (let ((x (term-cursor-x term))
                  (y (term-cursor-y term)))
              (cond
               ((and (= cw 2) (>= (+ x 1) w))
                (set-term-cell-at! term x y #\space face)
                (set-term-cursor-x! term 0)
                (cond
                 ((= y (term-scroll-bottom term))
                  (term-scroll-up! term 1))
                 (else
                  (set-term-cursor-y! term (+ y 1))))
                (let ((x2 (term-cursor-x term))
                      (y2 (term-cursor-y term)))
                  (set-term-cell-at! term x2 y2 ch face)
                  (when (and (= cw 2) (< (+ x2 1) w))
                    (set-term-cell-at! term (+ x2 1) y2 #\space face))
                  (set-term-cursor-x! term (+ x2 cw))))
               (else
                (set-term-cell-at! term x y ch face)
                (when (and (= cw 2) (< (+ x 1) w))
                  (set-term-cell-at! term (+ x 1) y #\space face))
                (set-term-cursor-x! term (+ x cw))))))
          (loop (+ idx 1)))))))
